import type { Metadata } from "next";
import { Inter, Inconsolata } from "next/font/google";
import LocalFont from "next/font/local";
import "./globals.css";
import localFont from 'next/font/local';
import Nav from "./components/navbar/Nav";
import SmoothScroll from "./components/SmoothScroll";
import { ViewProvider } from "./utils/context/ViewContext";
import IntroAnimation from "./components/IntroAnimation";


const montreal = localFont({
  src: '../app/fonts/NeueMontreal.woff2',
  variable: '--montreal'
})

const clashGrotesk = localFont({
  src: '../app/fonts/ClashGrotesk-Variable.woff2',
  variable: '--clash-grotesk'
})

const inconsolata = Inconsolata({
  variable: "--font-inconsolata",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  // modal
}: Readonly<{
  children: React.ReactNode;
  // modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inconsolata.variable} ${inter.variable} ${montreal.variable} ${clashGrotesk.variable} antialiased`}
      >
        <IntroAnimation />
        <ViewProvider>
          <SmoothScroll>
            {/* {modal} */}
            {children}
          </SmoothScroll>
        </ViewProvider>
      </body>

    </html>
  );
}
