import type { Metadata } from "next";
import { Inter, Inconsolata } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';
import Nav from "./components/navbar/Nav";
import SmoothScroll from "./components/SmoothScroll";

const clashGrotesk = localFont({
  src: '../app/fonts/ClashGrotesk-Variable.woff2',
  variable: '--clash-grotesk'
})

const inconsolata = Inconsolata({
  variable: "--font-inconsolata",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inconsolata.variable} ${inter.variable} ${clashGrotesk.variable} antialiased`}
      >
        <SmoothScroll>
          <Nav />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
